ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/(integration|unit)/data/
      - id: end-of-file-fixer
        exclude: ^(tests/(integration|unit)/data/|LICENSE|.python-version-default)
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer

  - repo: https://github.com/Spill-Tea/addlicense-pre-commit
    rev: v1.2.0
    hooks:
      - id: addlicense
        entry: addlicense-pre-commit
        language: golang
        exclude: ^docs/
        args: [ -f, LICENSE ]
        types_or: [ python, cython, c ]
